mysite/myquestsite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

app_name = 'questapp'

urlpatterns = [
    url(r'', include('questapp.urls')),
    url(r'^admin/', admin.site.urls),
]

mysite/questapp/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login, logout
from . import views

app_name = 'questapp'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),

    url(r'^(?P<pk>[0-9]+)/$', views.QuestionnaireView.as_view(), name='detail'),

    url(r'^login/$', login, {'template_name': 'auth/login.html'}, name='login'),

    url(r'^logout/$', logout, {'next_page': '/'}, name='logout'),

    url(r'^signup/$', views.signup, name='signup'),

    url(r'^add_questionnaire/$', views.QuestionnaireAddView.as_view(),  name='create_questionnaire'),

    url(r'^(?P<pk>[0-9]+)/delete_questionnaire/$', views.QuestionnaireDeleteView.as_view(), name='delete_questionnaire'),

    url(r'^(?P<questionnaire_id>[0-9]+)/result/$', views.result, name='result'),

    url(r'^(?P<questionnaire_id>[0-9]+)/add_question/$', views.CreateQuestion.as_view(), name='add_question'),

    url(r'^(?P<question_id>[0-9]+)/manage_answers/$', views.manage_answers, name='manage_answers'),

    url(r'^(?P<pk>[0-9]+)/edit_questionnaire/$', views.QuestionnaireChangeView.as_view(), name='edit_questionnaire'),

    url(r'^(?P<pk>[0-9]+)/question_detail/$', views.QuestionView.as_view(), name='question_detail'),

    url(r'^(?P<pk>[0-9]+)/edit_question/$', views.QuestionChangeView.as_view(), name='edit_question'),

    url(r'^(?P<pk>[0-9]+)/delete_question/$', views.QuestionDeleteView.as_view(), name='delete_question'),

]

mysite/questapp/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError


class Questionnaire(models.Model):
    user = models.ForeignKey(User)
    test_name = models.CharField(max_length=200)
    test_description = models.CharField(max_length=1000)
    passed_over = models.IntegerField(default=50)
    creation_date = models.DateField(auto_now_add=True)
    questions_per_page = models.IntegerField(default=5)

    def __str__(self):
        return self.test_name

    class Meta:
        ordering = ['-creation_date']

    def get_absolute_url(self):
        return reverse('questapp:detail', kwargs={'pk': self.pk})

    def validate_unique(self, exclude=None):
        qs = Questionnaire.objects.filter(test_name=self.test_name)
        if qs.exists():
            raise ValidationError('Questionnaire with that name already exists')
        super(Questionnaire, self).validate_unique(exclude)

    def save(self, *args, **kwargs):
        self.validate_unique()
        super(Questionnaire, self).save(*args, **kwargs)


class Question(models.Model):
    test = models.ForeignKey(Questionnaire, on_delete=models.CASCADE)
    question_text = models.CharField(max_length=300)
    page_number = models.IntegerField(default=1)

    def __str__(self):
        return self.question_text

    def get_absolute_url(self):
        return reverse('questapp:detail', kwargs={'pk': self.pk})


class Answers(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    answer_text = models.CharField(max_length=300)
    score = models.IntegerField(default=0)

    def __str__(self):
        return self.answer_text

mysite/questapp/forms.py
from django.contrib.auth.models import User
from .models import Questionnaire, Answers, Question
from django import forms


class SignUpForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'password']


class QuestionnaireForm(forms.ModelForm):
    test_name = forms.CharField(widget=forms.TextInput(attrs={'size': 80}))
    test_description = forms.CharField(widget=forms.TextInput(attrs={'size': 80}))

    class Meta:
        model = Questionnaire
        fields = ['test_name', 'test_description', 'passed_over']


class QuestionForm(forms.ModelForm):
    question_text = forms.CharField(widget=forms.TextInput(attrs={'size': 80}))

    class Meta:
        model = Question
        fields = ['question_text', ]


class AnswersForm(forms.ModelForm):
    class Meta:
        model = Answers
        fields = ['answer_text', 'score']

mysite/questapp/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db import transaction
from django.shortcuts import render, get_object_or_404, redirect
from django.core.urlresolvers import reverse_lazy
from .models import Questionnaire, Question, Answers
from django.contrib.auth import login, authenticate
from .forms import SignUpForm, QuestionnaireForm, QuestionForm
from django.views.generic import ListView, CreateView, DeleteView, UpdateView, DetailView
from django.db.models import Max
from django.forms import inlineformset_factory
from braces.views import LoginRequiredMixin


from django.forms.utils import ErrorList
from django import forms


class IndexView(ListView):
    model = Questionnaire
    context_object_name = 'questionnaires'
    template_name = 'questapp/index.html'
    paginate_by = 5


class QuestionnaireView(ListView):
    template_name = 'questapp/detail.html'
    success_url = reverse_lazy('questapp:index')

    def get_queryset(self):
        return Question.objects.filter(test=Questionnaire.objects.get(pk=self.kwargs['pk'])).order_by('page_number')

    def get_context_data(self, **kwargs):
        context = super(QuestionnaireView, self).get_context_data(**kwargs)
        questionnaire = Questionnaire.objects.get(pk=self.kwargs['pk'])
        context['questionnaire'] = questionnaire
        questions = Question.objects.filter(test=questionnaire).order_by('page_number')
        paginator = Paginator(questions, questionnaire.questions_per_page)
        page = self.request.GET.get('page')
        try:
            questions = paginator.page(page)
        except PageNotAnInteger:
            questions = paginator.page(1)
        except EmptyPage:
            questions = paginator.page(paginator.num_pages)
        context['questions'] = questions
        return context


def signup(request):

    form = SignUpForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect('/')

    form = SignUpForm()
    return render(request, 'questapp/signup.html', {'form': form})


class QuestionnaireAddView(LoginRequiredMixin, CreateView):
    model = Questionnaire
    template_name = 'questapp/base_create.html'
    success_url = 'questapp:index'
    form_class = QuestionnaireForm

    def get_success_url(self):
        return reverse_lazy(self.success_url)

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(QuestionnaireAddView, self).form_valid(form)


class QuestionnaireDeleteView(LoginRequiredMixin, DeleteView):
    model = Questionnaire
    template_name = 'questapp/confirm_delete.html'
    template_name_suffix = '_confirm_delete'
    success_url = 'questapp:index'

    def get_object(self, queryset=None):
        obj = super(QuestionnaireDeleteView, self).get_object()
        self.questionnaire = get_object_or_404(Questionnaire, pk=obj.pk)
        return obj

    def get_success_url(self):
        return reverse_lazy(self.success_url)


class QuestionnaireChangeView(LoginRequiredMixin, UpdateView):
    model = Questionnaire
    fields = ['test_name', 'test_description', 'passed_over']
    template_name = 'questapp/base_create.html'
    success_url = 'questapp:index'

    def get_success_url(self):
        return reverse_lazy(self.success_url)


class CreateQuestion(LoginRequiredMixin, CreateView):
    template_name = 'questapp/base_create.html'
    model = Question
    form_class = QuestionForm
    success_url = 'questapp:detail'

    def get_success_url(self):
        return reverse_lazy(self.success_url, kwargs={'pk': self.kwargs['questionnaire_id']})

    def form_valid(self, form):
        questionnaire = Questionnaire.objects.get(pk=self.kwargs['questionnaire_id'])
        questions = Question.objects.filter(test=questionnaire)
        form.instance.test = questionnaire

        question_list = list(questions.values_list('question_text', flat=True))
        if self.request.POST.get('question_text') in question_list:
            form._errors[forms.forms.NON_FIELD_ERRORS] = ErrorList([
                u'A question with that text for the questionnaire -- {} -- already exists'.format(questionnaire.test_name)
            ])
            return self.form_invalid(form)

        return super(CreateQuestion, self).form_valid(form)


class QuestionView(LoginRequiredMixin, DetailView):
    model = Question
    template_name = 'questapp/question_detail.html'

    def get_context_data(self, **kwargs):
        context = super(QuestionView, self).get_context_data(**kwargs)
        question = Question.objects.get(pk=self.kwargs['pk'])
        answers = Answers.objects.filter(question=question)
        context['question'] = question
        context['answer'] = answers
        return context


class QuestionChangeView(LoginRequiredMixin, UpdateView):
    model = Question
    form_class = QuestionForm
    template_name = 'questapp/base_create.html'
    success_url = 'questapp:question_detail'

    def get_success_url(self):
        return reverse_lazy(self.success_url, kwargs={'pk': self.kwargs['pk']})


class QuestionDeleteView(LoginRequiredMixin, DeleteView):
    model = Question
    template_name = 'questapp/confirm_delete.html'
    template_name_suffix = '_confirm_delete'
    success_url = 'questapp:detail'

    def get_object(self, queryset=None):
        obj = super(QuestionDeleteView, self).get_object()
        self.question = get_object_or_404(Question, pk=obj.pk)
        self.questionnaire = Questionnaire.objects.get(pk=self.question.test.id)
        return obj

    def get_success_url(self):
        return reverse_lazy(self.success_url, kwargs={'pk': self.questionnaire.id})


@login_required
@transaction.atomic
def manage_answers(request, question_id):
    if question_id:
        question = get_object_or_404(Question, pk=question_id)
    else:
        question = Question()

    answers_formset = inlineformset_factory(Question, Answers, fields=['answer_text', 'score'], can_delete=True, extra=1)

    if request.method == "POST":
        formset = answers_formset(request.POST, request.FILES, instance=question)
        if formset.is_valid():
            formset.save()
            return redirect('questapp:question_detail', pk=question_id)
    else:
        formset = answers_formset(instance=question)
    return render(request, 'questapp/manage_answers.html', {
        'formset': formset,
    })


def result(request, questionnaire_id):
    checked = []
    score, max_score, max_possible = 0, 0, 0
    better_answers = []
    questionnaire = get_object_or_404(Questionnaire, pk=questionnaire_id)
    questions = Question.objects.filter(test=questionnaire).order_by('page_number')
    for question in questions:
        answers = Answers.objects.filter(question=question)
        max_score = answers.aggregate(Max('score'))['score__max']
        if max_score is not None:
            max_possible += max_score
            post_question = 'question' + str(question.id)
            if post_question in request.POST:
                answer_id = int(request.POST.get(post_question))
                myanswer = Answers.objects.get(pk=answer_id)
                checked.append(answer_id)
                score += myanswer.score
                if myanswer.score < max_score:
                    better_answer = answers.filter(score=max_score)[0]
                    a = [item for item in better_answers if item[0] == question.page_number]
                    if len(a) == 0 or len(better_answers) == 0:
                        better_answers.append((
                            question.page_number,
                            question.question_text,
                            better_answer.answer_text,
                            better_answer.score
                        ))
        if score < questionnaire.passed_over:
            message_text = 'you failed the test'
        else:
            message_text = 'you passed the test'
    if len(checked) == len(questions):
        return render(request, 'questapp/result.html', {
            'questionnaire': questionnaire,
            'score': str(score),
            'max_score': str(max_possible),
            'better_answers': better_answers,
            'message_text': message_text,
        })
    else:
        return render(request, 'questapp/detail.html', {
                'questions': questions,
                'questionnaire': questionnaire,
                'checked': checked,
                'error_message': 'you need to answer to {} more questions'.format(str(len(questions)-len(checked)))
            })

mysite/questapp/templates/questapp/base.html
<! DOCTYPE html>
{% load i18n %}
{% load static %}
<html lang="en">

<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static 'questapp/font-awesome-4.7.0/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'questapp/style.css' %}" type="text/css" />


</head>

<body>

    {% if user.is_authenticated %}

    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <p class="navbar-text"><i class="fa fa-user" aria-hidden="true"></i> {{user.username}}</p>
            </div>
            <ul class="nav navbar-nav navbar-right" style="list-style-type: none;">
                <li class="active"><a class="nav-link" href="{% url 'questapp:index' %}"><i class="fa fa-home" aria-hidden="true"></i>Home</a>
                <li><a class="navbar-link" href="{% url 'questapp:logout' %}"><i class="fa fa-sign-out" aria-hidden="true"></i>Log Out</a></li>
            </ul>
        </div>
    </nav>

    {% else %}


      <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <p class="navbar-text"><i class="fa fa-user" aria-hidden="true"></i>  Anonymous</p>
            </div>
            <ul class="nav navbar-nav navbar-right" style="list-style-type: none;">
                <li class="active"><a class="nav-link" href="{% url 'questapp:index' %}"><i class="fa fa-home" aria-hidden="true"></i>Home</a></li>
                <li><a class="nav-link" href="{% url 'questapp:login' %}"><i class="fa fa-sign-in" aria-hidden="true"></i>Log In</a></li>
                <li><a class="nav-link" href="{% url 'questapp:signup' %}"><i class="fa fa-user-plus" aria-hidden="true"></i>Sign Up</a></li>
            </ul>
        </div>
    </nav>

    {% endif %}
    {% block header %}
    {% endblock %}

    {% block content %}
    {% endblock %}

</body>
</html>

mysite/questapp/templates/questapp/base_create.html
{% extends 'questapp/base.html' %}

{% block content %}

<div class="container"><strong style="color:red"> {{ form.non_field_errors }} </strong></div>
<div class="container">
<form class="form-horizontal" method="post">{% csrf_token %}
    <fieldset  class="control-group">
        {% for field in form %}
            {% if field.errors %}
                <div class="control-group error">
                    <label class="control-label">{{ field.label }}</label>
                    <div class="controls">{{ field }}
                        <span class="help-inline">
                            {% for error in  field.errors %}{{ error }}{% endfor %}
                        </span>
                    </div>
                </div>
            {% else %}
                <div class="control-group">
                    <label class="control-label">{{ field.label }}</label>
                    <div class="controls">{{ field }}
                        {% if field.help_text %}
                            <p class="help-inline"><small>{{ field.help_text }}</small></p>
                        {% endif %}
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    </fieldset>
    <hr/>
    <div class="form-actions">
        <button type="submit" class="btn btn-primary" >Submit</button>
    </div>
</form>
</div>
{% endblock %}

mysite/questapp/templates/questapp/confirm_delete.html
{% extends "questapp/base.html" %}

{% block content %}
    <div id="content-container" class="container p-none">
        <div class="side-p">
            <h3>Are you sure?</h3>
            <p>You're about to delete {{ object }}. Please confirm.</p>
            <form action="" method="post">
                {% csrf_token %}
                <input class="btn btn-link"
                       type="button" value="Cancel"
                       onclick="window.history.go(-1);"/>
                <input class="btn btn-danger" type="submit" value="Confirm"/>
            </form>
        </div>
    </div>
{% endblock %}

mysite/questapp/templates/questapp/detail.html
{% extends 'questapp/base.html' %}

{% block content %}

{% if error_message %}
    <div class="text-center">
        <strong style="color: red"> {{ error_message }}
        </strong>
    </div>
{% endif %}

<div class="text-center"><strong>{{ questionnaire.test_name }} : {{questionnaire.test_description}}</strong></div><hr>

{% if questions %}
      <div class="container">
        <form class="form-horizontal" action="{% url 'questapp:result' questionnaire.id %}" method="post">
            {% csrf_token %}

            {% for question in questions %}
                <div class=" container text-center">
                    <a href="{% url 'questapp:question_detail' question.id %}"><i class="fa fa-question-circle-o" aria-hidden="true"></i>
                        question: {{forloop.counter}} -- {{ question.question_text }}
                    </a>
                    {% for answer in question.answers_set.all %}
                    <div class="container text-center radio">
                        {% if answer.id in checked %}
                            <input type="radio" name="question{{question.id}}" id="question{{question.id}}" value="{{answer.id}}" checked="checked"/>
                        {% else %}
                            <input type="radio" name="question{{question.id}}" id="question{{question.id}}" value="{{answer.id}}" />
                        {% endif %}
                        <label for ="question{{question.id}}">{{answer.answer_text}} </label>
                     </div>
                    {% endfor %}
                </div> </br>
            {% endfor %}
            <hr/>
             <div class="text-center"> <input type="submit" value="Vote" class="btn btn-primary"/> </div>
        </form>
      </div>
<div class="pagination text-center">
    <span class="step-links">
        {% if questions.has_previous %}
            <a href="?page={{ questions.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ questions.number }} of {{ questions.paginator.num_pages }}.
        </span>

        {% if questions.has_next %}
            <a href="?page={{ questions.next_page_number }}">next</a>
        {% endif %}
    </span>
</div>
{% else %}
<div class="text-center"><mark style="color: red">No questions to show</mark></div>
</br>
{% endif %}
 {% if user.is_authenticated %}
     <div class="text-center">
                <a href="{% url 'questapp:edit_questionnaire' questionnaire.id %}" class="btn btn-primary"><i class="fa fa-pencil-square" aria-hidden="true"></i>  Edit Questionnaire</a>
                <a href="{% url 'questapp:delete_questionnaire' questionnaire.id %}" class="btn btn-danger"><i class="fa fa-trash" aria-hidden="true"></i>  Delete Questionnaire</a>
                <a href="{% url 'questapp:add_question' questionnaire.id %}" class="btn btn-primary"><i class="fa fa-plus" aria-hidden="true"></i>  Add Question</a>
     </div>
{% endif %}


{% endblock %}

mysite/questapp/templates/questapp/index.html
{% extends "questapp/base.html" %}



{% block content %}

{% if questionnaires %}

    {% for questionnaire in questionnaires %}
    <div class="text-center">
        <a class="text-center" href="{% url 'questapp:detail' questionnaire.id %}" ><i class="fa fa-quora" aria-hidden="true"></i>
            {{ questionnaire.test_name }} : {{questionnaire.test_description}}
        </a>
    </div>

    <hr>
    {% endfor %}

    {% include 'questapp/paginator.html'%}
{% else %}
    <div class="text-center"><mark>No questionnaires to show</mark></div>
{% endif %}

{% if user.is_authenticated %}
    <div class="text-center">
        <li><a class="btn btn-primary" href="{% url 'questapp:create_questionnaire' %}"><i class="fa fa-plus" aria-hidden="true"></i>  Add Questionnaire</a></li>
    </div>
{% endif %}

{% endblock %}

mysite/questapp/templates/questapp/manage_answers.html
{% extends 'questapp/base.html' %}
{% load formset_tags %}
{% load i18n %}
{% block content %}

    <form method="post">
        {% csrf_token %}
        {% if formset %}
            {{ formset.management_form }}
            <div class="formset">
                {% for form in formset %}
                    <div>{{ form.as_table }}</div>
                    {% endfor %}
            </div>
                 {% if formset.non_form_errors %}
                    {% for error in formset.non_form_errors %}
                        {{ error|escape }}
                    {% endfor %}
                {% endif %}
        {% endif %}

        <button class="btn btn-primary" type="submit">{% trans "Save" %}</button>

    </form>
    <script>('.formset').formset({
                    });
     </script>
{% endblock %}

mysite/questapp/templates/questapp/paginator.html
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if contacts.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
        {% endif %}
    </span>
</div>

mysite/questapp/templates/questapp/question_detail.html
{% extends 'questapp/base.html' %}


{% block content %}


{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

 <div class="text-center">{{ question.question_text }}</div><hr>
        <div class="text-center">
            {% for answer in question.answers_set.all %}
            <div style="font-size: 20">
                <strong><i class="fa fa-arrows-h" aria-hidden="true"></i>
                    <span style="color: blue">answer{{forloop.counter}}:</span>  {{answer.answer_text}}
                </strong>
            </div> </br>
            {% endfor %}
        </div>
<hr/>
 {% if user.is_authenticated %}
     <div class="text-center">
                <a href="{% url 'questapp:edit_question' question.id %}" class="btn btn-primary"><i class="fa fa-pencil-square" aria-hidden="true"></i>  Edit Question</a>
                <a href="{% url 'questapp:delete_question' question.id %}" class="btn btn-danger"><i class="fa fa-trash" aria-hidden="true"></i>  Delete Question</a>
                <a href="{% url 'questapp:manage_answers' question.id %}" class="btn btn-primary"><i class="fa fa-pencil-square" aria-hidden="true"></i>  Manage Answers</a>
     </div>

{% endif %}


{% endblock %}

mysite/questapp/templates/questapp/result.html
{% extends 'questapp/base.html' %}

{% block content %}
<div class="container text-center">
    <p>For the test --- {{questionnaire.test_name}}</p>
    <p><strong>You're score is {{score}} out of {{max_score}}</strong></p>
    <div class="actions">{{message_text}}</div>


    {% if better_answers %}
        <p>You're score would have been better if you wold have answer this way:</p>
        {% for p, q, a, s in better_answers %}
            <p> On page: {{p}}</p>
            <p> At question: {{q}}</p>
            <p>better response would have been </p>
            <p>{{a}} with a score of {{s}}</p>

        {% endfor %}
    {% else %}
        <p> Congrats, all your answers were correct </p>
    {% endif %}
</div>
{% endblock %}

mysite/questapp/templates/questapp/signup.html
{% extends 'questapp/base.html' %}

{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}